package io.github.pawgli.publishing

internal object PublishingPropertyKey {
  const val VERSION_SYSTEM_ENV = "PUBLISHING_LIBRARY_VERSION_SYSTEM_ENV"

  const val NAME = "PUBLISHING_LIBRARY_NAME"
  const val DESCRIPTION = "PUBLISHING_LIBRARY_DESCRIPTION"
  const val REPO_URL = "PUBLISHING_REPO_URL"
  const val LICENSE = "PUBLISHING_LICENSE"
  const val LICENSE_URL = "PUBLISHING_LICENSE_URL"
  const val SCM_CONNECTION = "PUBLISHING_SCM_CONNECTION"
  const val ARTIFACT_ID = "PUBLISHING_ARTIFACT_ID"
}
